### ISSUE TITLE
set up instructions?

### ISSUE THREAD

**Issue by joereynolds** [metulburr/python-gaming.com#2]
I've cloned the repo and am currently jumping through hoops to try and get it to work. 

I've installed the `php5-mysql` extension that wordpress needs but now there are DB connection errors. Are there any automated builds of the database or do I need to create the tables myself?
If so, what needs creating in order to see the site as it is live?

All of the pages look off and are missing sections though I'm guessing that's because wordpress can't connect to do its thing. Some pages also seem to be using ASP or am I wrong there?

Any help would be muchos appreciated :)

**Comment by metulburr** [comment]
A dev site can be created locally in ubuntu using this tutorial. Im not sure for mac or windows. 
https://www.jackreichert.com/2014/08/setting-up-an-ubuntu-desktop-lamp-development-server/

The difference from the tutorial...

As for wordpress database issues, create a MySQL database with the same database name and password as in /var/www/html/blog/wordpress/wp-config.php

And instead of installing wordpress, you just copy the repo content to /var/www/html

I believe this should work.
